name: Code Quality and Security
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install npm
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.PS_GITHUB_ACCESSTOKEN }}
      - name: Test npm
        run: npm run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.PS_SONAR_KEY }}
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.PS_SNYK_API_TOKEN }}
        with:
          args: --severity-threshold=high
          command: test
